//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por pia.rc
//
#define IDD_MAIN_WINDOW                 101
#define IDD_MEDICO                      103
#define IDD_PACIENTE                    105
#define IDD_ESPECIALIDAD                107
#define IDD_AGENDAR_CITAS               109
#define IDD_REPORTE_CITAS_MEDICO        111
#define IDD_REPORTE_PACIENTE            113
#define IDD_CONSULTORIO                 115
#define IDR_MENU1                       117
#define INGRESAR_BTN                    1001
#define IDC_USUARIO_ADMIN               1002
#define IDC_PASS_ADMIN                  1003
#define BUSCAR_MEDICO_BTN               1004
#define LIST_INFO_MEDICOS               1005
#define IDC_BUSCAR_MEDICO               1006
#define APLICAR_MEDICO_BTN              1007
#define IDC_CEDULA_INFO_MEDICO          1008
#define IDC_NOMBRES_INFO_MEDICO         1009
#define IDC_PATERNO_INFO_MEDICO         1010
#define IDC_MATERNO_INFO_MEDICO         1011
#define IDC_EMAIL_INFO_MEDICO           1012
#define IDC_TEL_INFO_MEDICO             1013
#define IDC_ACTIVO_MEDICO               1017
#define IDC_INACTIVO_MEDICO             1018
#define IDC_LIMPIAR_MEDICO              1019
#define HOMBRE_PACIENTE                 1019
#define LIST_INFO_PACIENTES             1020
#define IDC_BUSCAR_PACIENTE             1021
#define BUSCAR_PACIENTE_BTN             1022
#define IDC_LIMPIAR_PACIENTE            1023
#define MUJER_PACIENTE                  1024
#define NACIMIENTO_INFO_PACIENTE        1025
#define ID_INFO_PACIENTE                1026
#define NOMBRES_INFO_PACIENTE           1027
#define PATERNO_INFO_PACIENTE           1028
#define MATERNO_INFO_PACIENTE           1029
#define EMAIL_INFO_PACIENTE             1030
#define TEL_INFO_PACIENTE               1031
#define ACTIVO_PACIENTE                 1032
#define INACTIVO_PACIENTE               1033
#define APLICAR_PACIENTE_BTN            1034
#define IDC_BUSCAR_ESP                  1035
#define BUSCAR_ESP_BTN                  1036
#define LIMPIAR_ESP_BTN                 1037
#define ID_INFO_ESP                     1038
#define NOMBRE_INFO_ESP                 1039
#define APLICAR_ESP_BTN                 1040
#define LIST_CONSULTORIOS               1042
#define AGENDAR_CITA_BTN                1043
#define COMBO_ESPECIALIDAD_AGENDAR      1044
#define DISPONIBILIDAD_CITA_BTN         1045
#define NOMBRE_AGENDAR                  1046
#define PATERNO_AGENDAR                 1047
#define MATERNO_AGENDAR                 1048
#define HOMBRE_AGENDAR                  1049
#define MUJER_AGENDAR                   1050
#define EDAD_AGENDAR                    1051
#define FECHA_CITA_AGENDAR              1052
#define FILTRAR_FECHAS_REPORTE_PACIENTE 1053
#define FIN_REPORTE_PACIENTE            1054
#define BUSCAR_REPORTE_PACIENTE_BTN     1055
#define INICIO_REPORTE_MEDICO           1056
#define FIN_REPORTE_MEDICO              1057
#define NOMBRE_MEDICO_AGENDAR           1057
#define FILTRAR_FECHAS_REPORTE_MEDICO   1058
#define PATERNO_MEDICO_AGENDAR          1058
#define CEDULA_REPORTE_MEDICO           1059
#define MATERNO_MEDICO_AGENDAR          1059
#define BUSCAR_REPORTE_MEDICO_BTN       1060
#define LIST_CITAS_MEDICO               1061
#define INICIO_REPORTE_PACIENTE         1062
#define ID_REPORTE_PACIENTE             1063
#define CANCELAR_CITA_PACIENTE          1065
#define HORA_CITA_AGENDAR               1066
#define CITA_BTN                        1067
#define COMBO_ESPECIALIDAD              1069
#define IDC_APLICAR_CONSULTORIO         1070
#define IDC_ID_CONSULTORIO              1072
#define COMBO_MEDICOS                   1073
#define IDC_ESPECIALIDAD_CONSULTORIO    1074
#define BTN_BUSCAR_CONSULTORIO          1076
#define IDC_LIMPAR_CONSULTORIO          1077
#define BUSCAR_CONSULTORIO              1078
#define STATIC_CEDULA_MEDICO            1079
#define LIST_PACIENTES_REPORTE          1080
#define LIST_CITAS_PACIENTE             1081
#define STATIC_FECHA_HORA_CITA_PACIENTE 1082
#define DIAGNOSTICO_REPORTE_PACIENTE    1083
#define ID_PACIENTE_REPORTE_PACIENTE    1084
#define NOMBRES_PACIENTE_REPORTE_PACIENTE 1085
#define PATERNO_PACIENTE_REPORTE_PACIENTE 1086
#define CEDULA_MEDICO_REPORTE_PACIENTE  1087
#define MATERNO_PACIENTE_REPORTE_PACIENTE 1088
#define NOMBRES_MEDICO_REPORTE_PACIENTE 1089
#define PATERNO_MEDICO_REPORTE_PACIENTE 1090
#define MATERNO_MEDICO_REPORTE_PACIENTE 1091
#define COMBO_ESPECIALIDAD_REPORTE_MEDICO 1092
#define MOSTRAR_MEDICOS_REPORTE_MEDICO  1093
#define LIST_MEDICOS_REPORTE            1094
#define ID_PACIENTE_REPORTE_MEDICO      1095
#define NOMBRES_PACIENTE_REPORTE_MEDICO 1096
#define PATERNO_PACIENTE_REPORTE_MEDICO 1097
#define MATERNO_PACIENTE_REPORTE_MEDICO 1098
#define CEDULA_MEDICO_REPORTE_MEDICO    1099
#define NOMBRES_MEDICO_REPORTE_MEDICO   1100
#define PATERNO_MEDICO_REPORTE_MEDICO   1101
#define MATERNO_MEDICO_REPORTE_MEDICO   1102
#define DIAGNOSTICO_REPORTE_MEDICO      1103
#define STATIC_FECHA_HORA_CITA_MEDICO   1104
#define GUARDAR_DIAGNOSTICO_BTN         1105
#define ID_M40001                       40001
#define ID_PACIENTE_REPORTEDECITAS      40002
#define ID_M40003                       40003
#define ID_MEDICO                       40004
#define ID_PACIENTE                     40005
#define ID_ESPECIALIDAD                 40006
#define ID_REPORTEDECITASM40007         40007
#define ID_REPORTEDECITASMEDICO         40008
#define ID_REPORTEDECITASPACIENTE       40009
#define ID_CONSULTORIO                  40010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        118
#define _APS_NEXT_COMMAND_VALUE         40011
#define _APS_NEXT_CONTROL_VALUE         1106
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
